apiVersion: apps/v1
kind: Deployment
spec:
  containers:
    - name: {{ .Char.Name }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
